# Generated by Django 5.1.2 on 2025-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa')], default='cod', max_length=20),
        ),
    ]
